(autogenerated assembly file by the compiler backend)
	file /Users/dwrr/root/projects/programming_language/new_cross_assembler2/library/core.s
	file /Users/dwrr/root/projects/programming_language/new_cross_assembler2/library/ascii.s
	file /Users/dwrr/root/projects/programming_language/new_cross_assembler2/library/useful.s
	set R0 0
	set R1 1
	set R2 01
	set R3 11
	set R4 001
	set R5 101
	set R6 011
	set R7 111
	set R8 0001
	set R9 1001
	set R10 0101
	set R11 1101
	set R12 0011
	set R13 1011
	set R14 0111
	set R15 1111

	riscv_hex

	ri r_imm r_add R0 R0 0000_0000_0000
	ri r_imm r_add R8 R0 1000_0000_0000
	ri r_imm r_add R1 R0 0001_0111_1100
	ri r_imm r_add R7 R1 0000_0000_0000
	ri r_imm r_add R1 R0 0000_0000_0000
	ri r_imm r_add R6 R1 0000_0000_0000
	ri r_imm r_add R1 R0 0000_0000_0000
	ri r_imm r_add R5 R1 0000_0000_0000

at L8
	ri r_imm r_add R1 R0 0100_0000_0000
	ri r_imm r_add R4 R1 0000_0000_0000

at L11
	ri r_imm r_add R3 R5 0000_0000_0000
	ri r_imm r_add R2 R4 0000_0000_0000
	ri r_imm r_add R1 R8 0000_0000_0000
	rb r_branch r_blt R2 R3 L15
	ri r_imm r_add R1 R0 0000_0000_0000

at L15
	ri r_imm r_add R2 R1 0000_0000_0000
	rb r_branch r_beq R0 R2 L16
	rj r_jal R0 L17

at L16
	rj r_jal R0 L18

at L17
	ri r_imm r_add R2 R4 0000_0000_0000
	ri r_imm r_add R1 R5 0000_0000_0000
	rr r_reg r_remu R1 R1 R2 r_m
	ri r_imm r_add R1 R1 0000_0000_0000
	ri r_imm r_add R3 R0 0000_0000_0000
	ri r_imm r_add R2 R1 0000_0000_0000
	ri r_imm r_add R1 R8 0000_0000_0000
	rb r_branch r_beq R2 R3 L25
	ri r_imm r_add R1 R0 0000_0000_0000

at L25
	ri r_imm r_add R2 R1 0000_0000_0000
	rb r_branch r_beq R0 R2 L26
	rj r_jal R0 L27
	rj r_jal R0 L28

at L26

at L28
	ri r_imm r_add R2 R0 1000_0000_0000
	ri r_imm r_add R1 R4 0000_0000_0000
	rr r_reg r_add R1 R1 R2 0
	ri r_imm r_add R4 R1 0000_0000_0000
	rj r_jal R0 L11

at L18
	ri r_imm r_add R2 R0 1000_0000_0000
	ri r_imm r_add R1 R6 0000_0000_0000
	rr r_reg r_add R1 R1 R2 0
	ri r_imm r_add R6 R1 0000_0000_0000

at L27
	ri r_imm r_add R2 R0 1000_0000_0000
	ri r_imm r_add R1 R5 0000_0000_0000
	rr r_reg r_add R1 R1 R2 0
	ri r_imm r_add R5 R1 0000_0000_0000
	ri r_imm r_add R3 R7 0000_0000_0000
	ri r_imm r_add R2 R5 0000_0000_0000
	ri r_imm r_add R1 R8 0000_0000_0000
	rb r_branch r_blt R2 R3 L38
	ri r_imm r_add R1 R0 0000_0000_0000

at L38
	ri r_imm r_add R2 R1 0000_0000_0000
	rb r_branch r_blt R0 R2 L8
	(control flow termination point here)

eoi

