#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -Ofast -Weverything interpreter.c -o out

elif [ "clean" = "$1" ]; then
	rm -rf out
	rm -rf out.dSYM

elif [ "" = "$1" ]; then 
	clang -g -O0 -Weverything  -fsanitize=address,undefined interpreter.c -o out

else 
	echo "build: unknown target: $1"
fi

