// c source file auto-generated by my compiler.
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <stdio.h>
#include <errno.h>
#include <stdint.h>

static uint64_t x[4096];

static void ecall(void) {
	if (x[0] == 0) printf("debug: hello: %llu (0x%llx)\n", x[1], x[1]);
	else if (x[0] == 1) exit((int) x[1]);
	else if (x[0] == 2) { x[1] = (uint64_t) read((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 3) { x[1] = (uint64_t) write((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 4) { x[1] = (uint64_t) open((const char*) x[1], (int) x[2], (mode_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 5) { x[1] = (uint64_t) close((int) x[1]); x[2] = (uint64_t) errno; }
	else if (x[0] == 6) { x[1] = (uint64_t) (void*) mmap((void*) x[1], (size_t) x[2], (int) x[3], (int) x[4], (int) x[5], (off_t) x[6]); x[2] = (uint64_t) errno; }
	else if (x[0] == 7) { x[1] = (uint64_t) munmap((void*) x[1], (size_t) x[2]); x[2] = (uint64_t) errno; }
	else abort();
}

static uint8_t d[3] = {
	0x30, 0x31, 0x0a, 
};

int main(void) {
	x[4] = 0x0;
_173:;
	x[1] = 0x2;
_175:;
	if (x[1] >= x[4]) goto _176;
	x[0] = x[4];
	x[0] %= x[1];
	if (x[0] == 0x0) goto _178;
	x[1] += 0x1;
	goto _175;
_176:;
	x[5] = x[4];
_165:;
	x[0] = x[5];
	x[0] &= 0x1;
	if (x[0] == 0x0) goto _167;
	x[2] = ((uint64_t)(void*)d) + 0x1;
	x[0] = 0x3;
	x[1] = 0x1;
	x[3] = 0x1;
	ecall();
	goto _168;
_167:;
	x[2] = ((uint64_t)(void*)d) + 0x0;
	x[0] = 0x3;
	x[1] = 0x1;
	x[3] = 0x1;
	ecall();
_168:;
	x[5] >>= 0x1;
	if (x[5] != 0x0) goto _165;
	x[2] = ((uint64_t)(void*)d) + 0x2;
	x[0] = 0x3;
	x[1] = 0x1;
	x[3] = 0x1;
	ecall();
_178:;
	x[4] += 0x1;
	if (x[4] < 0x20000) goto _173;
	x[0] = 0x1;
	x[1] = 0x0;
	ecall();
_155:;
_158:;
_161:;
}
// (end of file)

