// c source file auto-generated by my compiler.
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <stdio.h>
#include <errno.h>
#include <stdint.h>

static uint64_t x[4096];

static void ecall(void) {
	if (x[0] == 0) printf("debug: hello: %llu (0x%llx)\n", x[1], x[1]);
	else if (x[0] == 1) exit((int) x[1]);
	else if (x[0] == 2) { x[1] = (uint64_t) read((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 3) { x[1] = (uint64_t) write((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 4) { x[1] = (uint64_t) open((const char*) x[1], (int) x[2], (mode_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 5) { x[1] = (uint64_t) close((int) x[1]); x[2] = (uint64_t) errno; }
	else if (x[0] == 6) { x[1] = (uint64_t) (void*) mmap((void*) x[1], (size_t) x[2], (int) x[3], (int) x[4], (int) x[5], (off_t) x[6]); x[2] = (uint64_t) errno; }
	else if (x[0] == 7) { x[1] = (uint64_t) munmap((void*) x[1], (size_t) x[2]); x[2] = (uint64_t) errno; }
	else abort();
}

static uint8_t d[12] = {
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x0a, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x0a, 
};

int main(void) {
	x[4] = 0x0;
_156:;
	x[0] = 0x3;
	x[1] = 0x1;
	x[2] = ((uint64_t)(void*)d) + 0x0;
	x[3] = 0x6;
	ecall();
	x[4] += 0x1;
	if (x[4] < 0x3) goto _156;
	x[4] = 0x0;
_159:;
	x[0] = 0x3;
	x[1] = 0x1;
	x[2] = ((uint64_t)(void*)d) + 0x6;
	x[3] = 0x6;
	ecall();
	x[4] += 0x1;
	if (x[4] < 0x5) goto _159;
	x[4] = 0x0;
_160:;
	x[0] = 0x3;
	x[1] = 0x1;
	x[2] = ((uint64_t)(void*)d) + 0x0;
	x[3] = 0x6;
	ecall();
	x[4] += 0x1;
	if (x[4] < 0x2) goto _160;
	x[0] = 0x1;
	x[1] = 0x0;
	ecall();
_157:;
_158:;
}
// (end of file)

