#!/bin/bash

# build file for msp430 programming with the assembler! 
# written on 1202509022.222902 by dwrr.

/Users/dwrr/root/personal/executables/assembler s.s && cp firmware.txt /Users/dwrr/Public/MSP_Flasher/firmware.txt
cd /Users/dwrr/Public/MSP_Flasher/
./program_msp430.sh firmware.txt
rm firmware.txt
cd -



