// c source file auto-generated by my compiler.
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <stdio.h>
#include <errno.h>
#include <stdint.h>

static uint64_t x[4096];

static void ecall(void) {
	if (x[0] == 0) printf("debug: hello: %llu (0x%llx)\n", x[1], x[1]);
	else if (x[0] == 1) exit((int) x[1]);
	else if (x[0] == 2) { x[1] = (uint64_t) read((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 3) { x[1] = (uint64_t) write((int) x[1], (void*) x[2], (size_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 4) { x[1] = (uint64_t) open((const char*) x[1], (int) x[2], (mode_t) x[3]); x[2] = (uint64_t) errno; }
	else if (x[0] == 5) { x[1] = (uint64_t) close((int) x[1]); x[2] = (uint64_t) errno; }
	else if (x[0] == 6) { x[1] = (uint64_t) (void*) mmap((void*) x[1], (size_t) x[2], (int) x[3], (int) x[4], (int) x[5], (off_t) x[6]); x[2] = (uint64_t) errno; }
	else if (x[0] == 7) { x[1] = (uint64_t) munmap((void*) x[1], (size_t) x[2]); x[2] = (uint64_t) errno; }
	else abort();
}
int main(void) {
	x[0] = 0;
	ecall();
	x[0] = 0x6;
	x[1] = 0x0;
	x[2] = 0x1000;
	x[3] = 0x3;
	x[4] = 0x1002;
	x[5] = 0xffffffffffffffff;
	x[6] = 0x0;
	ecall();
	x[0] = 0x1;
	x[0] = 0x0;
	x[1] = 0x0;
	ecall();
	x[0] = 0x1;
	x[1] = 0xc;
	ecall();
}
// (end of file)

