#!/bin/zsh

if [ "release" = "$1" ]; then
	clang -std=c99 -Ofast c.c -o run


elif [ "clean" = "$1" ]; then
	rm -rf run
	rm -rf run.dSYM


elif [ "" = "$1" ]; then 
	clang -g -O0 -std=c99 -Weverything -Wno-declaration-after-statement -Wno-poison-system-directories -fsanitize=address,undefined c.c -o run 

else 
	echo "build: unknown target: $1"
fi
