. a working exit program that executes on this macbook! 
  the first working executable generated by this assembler!
  written on 1202503064.102852 by dwrr
.

lf arm64.s

mov 16 1 0 2 1
mov 0 25 0 2 1
svc

